language: cpp
sudo: false
virtualenv:
  system_site_packages: true
python:
    - "2.7"
matrix:
  include:
    - os: osx
      osx_image: xcode7.3 # OS X 10.11.1
      compiler: clang
      before_install: ./install_osx_dependencies.sh
      install: ./install_dependencies.sh
      script: ./build.sh
      after_success: ./test_installation.sh

